secrets:
  create: false

serviceAccount: &serviceAccount arn:aws:iam::115216742450:role/eks-poc-argocd-role

argo-cd:
  image:
    tag: v2.1.6
    pullPolicy: IfNotPresent

  service:
    #type: ClusterIP
    type: LoadBalancer
