apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/conceptit/argo-cd-install.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values/development.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
